general:
  parameters:
    ASGDesiredCapacity: 2
    ASGMaxSize: 3
    ASGMinSize: 1
    DomainAdminPassword: dA5xL0lT9gH9hZ1h
    DomainAdminUser: Admin
    DomainDNSName: test.com
    DomainMemberSecurityGroup: sg-07f9dc182f98a297e
    DomainNetBIOSName: test
    ELBSchemeParameter: internet-facing
    IISServerInstanceType: 't3.2xlarge'
    PrivateSubnet1ID: subnet-07366fb19bcc6c009
    PrivateSubnet2ID: subnet-0bad84e1c7d121788
    ELBSubnet1ID: subnet-07e2c93e1caa03cfa
    ELBSubnet2ID: subnet-02528ce08672b9a9a
    QSS3KeyPrefix: quickstart-microsoft-iis/
    VPCID: vpc-07b03ee4d51e66ee6
project:
  name: quickstart-microsoft-iis
  owner: quickstart-eng@amazon.com
  regions:
  - us-east-1
  build_submodules: false
  package_lambda: false
tests:
  test-scenario1:
    template: ./templates/iis-workload.yaml
    regions:
    - us-east-1
    parameters:
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]