ssm_app_manager:
  should_upload: true
  documents_list:
    - document_name: AWSQuickStarts-Microsoft-IIS-Existing-VPC
      template_name: iis-workload.template.yaml
    - document_name: AWSQuickStarts-Microsoft-IIS
      template_name: iis-main.template.yaml
      has_nested_stacks: true
      nested_documents:
        - resource_name: VPCStack
          document_name: AWSQuickStarts-AWS-VPC
        - resource_name: IISStack
          document_name: AWSQuickStarts-Microsoft-IIS-Existing-VPC