// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM role that has the appropriate permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Ensure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.

// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Subscribe to the {partner-product-short-name} AMI

This Quick Start requires a subscription to the AMI for {partner-product-short-name} in AWS Marketplace.

. Sign in to your AWS account.
. {marketplace_listing_url}[Open the page for the {partner-product-short-name} AMI in AWS Marketplace], and then choose *Continue to Subscribe*.
. Review the terms and conditions for software usage, and then choose *Accept Terms*. +
  A confirmation page loads, and an email confirmation is sent to the account owner. For detailed subscription instructions, see the https://aws.amazon.com/marketplace/help/200799470[AWS Marketplace documentation^].

. When the subscription process is complete, exit out of AWS Marketplace without further action. *Do not* provision the software from AWS Marketplace—the Quick Start deploys the AMI for you.
endif::marketplace_subscription[]
// \Not to be edited

=== Launch the Quick Start

NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

. Sign in to your AWS account, and choose one of the following options to launch the AWS CloudFormation template. Each deployment takes about {deployment_time} to complete. For help choosing an option, see link:#_deployment_options[Deployment options], earlier in this guide.

[cols=2*]
|===
^|https://fwd.aws/wEMJ3[Deploy {partner-product-short-name} into a new VPC on AWS^]
^|https://fwd.aws/jnA6r[View template^]

^|https://fwd.aws/7zWJB[Deploy {partner-product-short-name} into an existing VPC on AWS^]
^|https://fwd.aws/jM3aD[View template^]
|===

// Adapt the following warning to your Quick Start.
WARNING: This Quick Start does not support https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html[shared subnets^]. If you deploy {partner-product-short-name} into an existing VPC, ensure that the VPC has two private subnets in different Availability Zones for the workload instances, and that the subnets aren’t shared. These subnets require https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html[NAT gateways^] in their route tables, to allow the instances to download packages and software without exposing them to the internet. Also, ensure that the domain name in the DHCP options is configured according to http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html[DHCP options sets^]. Provide your VPC settings when you launch the Quick Start.

[start=2]
. The AWS Region displayed in the upper-right corner of the navigation bar is where the {partner-product-short-name} network infrastructure is deployed in the N. Virginia ({default_deployment_region}) Region by default. Change it if necessary. 

// *Note:* This deployment includes Amazon EFS, which isn’t currently supported in all AWS Regions. For a current list of supported Regions, see the https://docs.aws.amazon.com/general/latest/gr/elasticfilesystem.html[endpoints and quotas webpage].

[start=3]
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. 
. Review the template parameters, and provide values for any parameters that require input. (For more information, see the link:#_parameter_reference[Parameter reference] section later in this guide.)

// In the following tables, parameters are listed by category and described separately for the two deployment options:

// * Parameters for deploying {partner-product-short-name} into a new VPC
// * Parameters for deploying {partner-product-short-name} into an existing VPC
