AWSTemplateFormatVersion: '2010-09-09'
Description: This CloudFormation Template demonstrates one ways to configure Windows Workloads with Auto-Scaling. IIS will be installed and configured to display a simple Static Page, 
  with CloudWatch Logs collecting Metrics and Logs and AWS Systems Manager configuring the instances. Scenario 1 launches a scalable IIS environment based on a launch template, Application
  Load Balancer and Auto Scaling Group. Configuration while Scaling is handled by Lifecycle Hooks, EventBridge, and AWS System Manager automation. (qs-1r91fg4hm)
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Launch into an existing VPC"
    Order: "2"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Active Directory Information
        Parameters:
          - DomainDNSName
          - DomainNetBIOSName
          - DomainAdminUser
          - DomainAdminPassword
      - Label:
          default: Autoscaling Group / Application Load Balancer Configuration
        Parameters:
          - ASGDesiredCapacity
          - ASGMaxSize
          - ASGMinSize
          - ELBSchemeParameter
          - WebAccessCIDR
          - IISServerInstanceType
      - Label:
          default: Network Configuration
        Parameters:
          - VPCID
          - DomainMemberSecurityGroup
          - PrivateSubnet1ID
          - PrivateSubnet2ID
          - ELBSubnet1ID
          - ELBSubnet2ID
      - Label:
          default: AWS Quick Start Configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels:
      ASGDesiredCapacity:
        default: Autoscaling group desired capacity
      ASGMaxSize:
        default: Autoscaling group max size
      ASGMinSize:
        default: Autoscaling group min size
      DomainDNSName:
        default: Domain DNS name
      DomainNetBIOSName:
        default: Domain NetBIOS name
      DomainAdminUser:
        default: Domain admin user name
      DomainAdminPassword:
        default: Domain admin password
      DomainMemberSecurityGroup:
        default: Security group with access to join domain
      ELBSchemeParameter:
        default: ELB Scheme
      ELBSubnet1ID:
        default: Subnet for ELB
      ELBSubnet2ID:
        default: Subnet for ELB
      IISServerInstanceType:
        default: Instance type for IIS Servers
      PrivateSubnet1ID:
        default: Private subnet 
      PrivateSubnet2ID:
        default: Private subnet
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      WebAccessCIDR:
        default: CIDR range that can access load balancers
      VPCID:
        default: VPC ID for workload
Parameters:
  ASGMinSize:
    Type: Number
    Description: Minimum instance size for the Auto Scaling Group.
  ASGMaxSize:
    Type: Number
    Description: Maximum instance size for the Auto Scaling Group.
  ASGDesiredCapacity:
    Type: Number
    Description: Desired capacity instance size for the Auto Scaling Group.
  DomainAdminPassword:
    AllowedPattern: (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*
    Description: Password for the domain admin user. Must be at least 8 characters,
      containing letters, numbers, and symbols.
    MaxLength: '32'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
  DomainAdminUser:
    AllowedPattern: '[a-zA-Z0-9]*'
    Default: Admin
    Description: User name for the account that will be used as domain administrator. This is separate from the default "Administrator" account.
    MaxLength: '25'
    MinLength: '5'
    Type: String
  DomainDNSName:
    AllowedPattern: '[a-zA-Z0-9\-]+\..+'
    Default: example.com
    Description: Fully qualified domain name (FQDN).
    MaxLength: '255'
    MinLength: '2'
    Type: String
  DomainNetBIOSName:
    AllowedPattern: '[a-zA-Z0-9\-]+'
    Default: EXAMPLE
    Description: NetBIOS name of the domain (up to 15 characters) for users of earlier
      versions of Windows.
    MaxLength: '15'
    MinLength: '1'
    Type: String
  DomainMemberSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Select EC2 security group that allows for Active Directory communication.
  ELBSchemeParameter:
    Type: String
    Default: internet-facing
    AllowedValues:
      - internet-facing
      - internal
    Description: Select whether the ELB is internet-facing (public) or internal (private).
  ELBSubnet1ID:
    Description: ID of the subnet 1 in Availability Zone 1 where the ALB will reside (e.g., subnet-a0246dcd)
      If internet-facing scheme was chosen select a public subnet, otherwise select private
    Type: AWS::EC2::Subnet::Id
  ELBSubnet2ID:
    Description: ID of the subnet 2 in Availability Zone 2 where the ALB will reside (e.g., subnet-a0246dcd)
      If internet-facing scheme was chosen select a public subnet, otherwise select private
    Type: AWS::EC2::Subnet::Id
  IISServerInstanceType:
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.12xlarge
      - c5.18xlarge
      - c5.24xlarge
      - r4.large
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - r5.12xlarge
      - r5.16xlarge
      - r5.24xlarge
    Default: t3.2xlarge
    Description: Amazon EC2 instance type for the second Active Directory instance
    Type: String
  PrivateSubnet1ID:
    Description: ID of the private subnet 1 in Availability Zone 1 for ec2 target group (e.g., subnet-a0246dcd)
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2ID:
    Description: ID of the private subnet 2 in Availability Zone 2 for ec2 target group (e.g., subnet-a0246dcd)
    Type: AWS::EC2::Subnet::Id
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: us-east-1
    Description: The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-microsoft-iis/
    Description: S3 key prefix for the Quick Start assets. This prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  WebAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Description: Allowed CIDR Block for external access to the ELBs.
    Type: String
  VPCID:
    Description: ID of the VPC (e.g., vpc-0343606e)
    Type: AWS::EC2::VPC::Id
Resources:
  ConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter30Days
            ExpirationInDays: 30
            Status: Enabled
            Prefix: 'logs/'
  DomainJoinSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'DomainJoinSecrets-${AWS::StackName}'
      Description: Secrets to join AD domain
      SecretString: !Sub '{"username":"${DomainNetBIOSName}\\${DomainAdminUser}","password":"${DomainAdminPassword}"}'
  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/security.template.yaml'
      Parameters:
        ConfigBucket: !Ref 'ConfigBucket'
        DomainJoinSecrets: !Ref 'DomainJoinSecrets'
        WebAccessCIDR: !Ref 'WebAccessCIDR'
        VPCID: !Ref 'VPCID'
        SetupConfigurationDocName: !Sub SetupConfiguration-${AWS::StackName}
        RemoveConfigurationDocName: !Sub RemoveConfigurationDocName-${AWS::StackName}
  AutomationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/automation-parts.template.yaml'
      Parameters:
        ConfigBucket: !Ref 'ConfigBucket'
        DomainJoinSecrets: !Ref 'DomainJoinSecrets'
        WriteS3LambdaRoleArn: !GetAtt 'SecurityStack.Outputs.WriteS3LambdaRoleArn'
        SetupConfigurationDocName: !Sub SetupConfiguration-${AWS::StackName}
        RemoveConfigurationDocName: !Sub RemoveConfigurationDocName-${AWS::StackName}
  WebAutoScaleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/asg-lch.template.yaml'
      Parameters:
        ConfigBucket: !Ref 'ConfigBucket'
        IISServerInstanceType: !Ref 'IISServerInstanceType'
        DomainMemberSecurityGroup: !Ref 'DomainMemberSecurityGroup'
        DomainDNSName: !Ref 'DomainDNSName'
        VPCID: !Ref 'VPCID'
        ELBSubnet1ID: !Ref 'ELBSubnet1ID'
        ELBSubnet2ID: !Ref 'ELBSubnet2ID'
        ELBSchemeParameter: !Ref 'ELBSchemeParameter'
        ASGDesiredCapacity: !Ref 'ASGDesiredCapacity'
        ASGMinSize: !Ref 'ASGMinSize'
        ASGMaxSize: !Ref 'ASGMaxSize'
        WorkloadSubnet1ID: !Ref 'PrivateSubnet1ID'
        WorkloadSubnet2ID: !Ref 'PrivateSubnet2ID'
        ExecutionResourceArn: !GetAtt 'SecurityStack.Outputs.ExecutionResourceArn'
        ExecutionRoleName: !GetAtt 'SecurityStack.Outputs.ExecutionRoleName'
        SetupConfigurationDocName: !GetAtt 'AutomationStack.Outputs.SetupConfigurationDocName'
        RemoveConfigurationDocName: !GetAtt 'AutomationStack.Outputs.RemoveConfigurationDocName'
        SSMInstanceProfileName: !GetAtt 'SecurityStack.Outputs.SSMInstanceProfileName'
        EventBridgeSSMAutoRole: !GetAtt 'SecurityStack.Outputs.EventBridgeSSMAutoRole'
        ALBSecurityGroup: !GetAtt 'SecurityStack.Outputs.ALBSecurityGroup'
        ALBListenersSecurityGroup: !GetAtt 'SecurityStack.Outputs.ALBListenersSecurityGroup'
Outputs:
  ConfigBucket:
    Value: !Ref ConfigBucket
  DomainJoinSecrets:
    Value: !Ref DomainJoinSecrets